# Generated by Django 6.0.6 on 2026-09-08 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injects', '0003_inject_description'),
        ('teams', '0004_teams_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injectsubmission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='injectsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='injectsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injectsubmission',
            name='graded_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='injectsubmission',
            name='inject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='injects.inject'),
        ),
        migrations.AlterField(
            model_name='injectsubmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inject_submissions', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='injectsubmission',
            unique_together={('inject', 'team')},
        ),
    ]
