# Generated by Django 6.0.6 on 2026-09-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_provisionedmachine_ip_address'),
        ('network', '0001_initial'),
        ('teams', '0004_teams_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_up', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_checks', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=3)),
                ('points_per_check', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_definitions', to='competitions.competition')),
                ('machine_template', models.ForeignKey(blank=True, help_text='Which VM type hosts this service. Leave blank to check all team VMs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.machinetemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='servicecheck',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='network.servicedefinition'),
        ),
        migrations.AddIndex(
            model_name='servicecheck',
            index=models.Index(fields=['service', 'team', 'checked_at'], name='network_ser_service_6c059d_idx'),
        ),
    ]
