# Generated by Django 6.0.6 on 2026-09-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_replace_machine_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetemplate',
            name='default_user',
            field=models.CharField(blank=True, default='', help_text='cloud-init username for this image (e.g. debian, ubuntu, rocky)', max_length=64),
        ),
    ]
