# Generated by Django 6.0.6 on 2026-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_add_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionedmachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
